name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install OpenSCAD
        run: sudo apt-get install openscad
      
      - name: Make assets directory
        run: mkdir assets
      
      - name: Compile firmware (Nano)
        uses: arduino/compile-sketches@v1.0.0
        with:
          sketch-paths: ./hotdog-fw
          fqbn: arduino:avr:nano
          cli-compile-flags: |
            - --export-binaries
            - --output-dir=assets
          libraries: |
            - name: AVR-context
              version: '0.9.1'
            - name: RF24
              version: '1.4.2'
            - name: BTLE
              version: '1.0.0'
      
      - name: Compile firmware (Nano Every)
        uses: arduino/compile-sketches@v1.0.0
        with:
          sketch-paths: ./hotdog-fw
          fqbn: arduino:megaavr:nona4809
          cli-compile-flags: |
            - --export-binaries
            - --output-dir=assets
          libraries: |
            - name: AVR-context
              version: '0.9.1'
            - name: RF24
              version: '1.4.2'
            - name: BTLE
              version: '1.0.0'

      - name: Copy firmware into assets
        run: cp hotdog-fw/hotdog-fw.ino assets
      
      - name: Build top casing
        run: openscad -o assets/hotdog-case-top.stl -D 'hotdog_top();' hotdog-hw/hotdog-case.scad
      
      - name: Build bottom casing
        run: openscad -o assets/hotdog-case-bottom.stl -D 'hotdog_bottom();' hotdog-hw/hotdog-case.scad
      
      - name: Render front PCB
        uses: INTI-CMNB/KiBot@v2_k6
        with:
          config: 'hotdog-hw/hotdog-pcb/kibot.yml'
          board: 'hotdog-hw/hotdog-pcb/hotdog-pcb-front.kicad_pcb'
          schema: 'hotdog-hw/hotdog-pcb/hotdog-pcb-front.kicad_sch'
          dir: assets

      - name: im not your maid kibot
        run: sudo rm -rf assets/pcbout

      - name: Render back PCB
        uses: INTI-CMNB/KiBot@v2_k6
        with:
          config: 'hotdog-hw/hotdog-pcb/kibot.yml'
          board: 'hotdog-hw/hotdog-pcb/hotdog-pcb-back.kicad_pcb'
          schema: 'hotdog-hw/hotdog-pcb/hotdog-pcb-back.kicad_sch'
          dir: assets

      - name: clean up your own shit
        run: sudo rm -rf assets/pcbout

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.version }}
          release_name: Version ${{ github.event.inputs.version }}
          draft: true
          prerelease: false

      - name: Upload Release Assets
        id: upload-release-assets
        uses: dwenegar/upload-release-assets@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
          assets_path: assets
          